"""add epic_key to user_tableau_custom_views

Revision ID: 44a4a3ce3141
Revises: f8954404f3b1
Create Date: 2026-03-24 17:02:02.049873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a4a3ce3141'
down_revision = 'f8954404f3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tableau_custom_views', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('epic_key', sa.String(length=32), nullable=True))
        batch_op.drop_column('project_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tableau_custom_views', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('project_key', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('epic_key')

    # ### end Alembic commands ###
