"""add epic_key to user_projects

Revision ID: c3d00bc3ae67
Revises: 
Create Date: 2026-03-18 18:35:02.656494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d00bc3ae67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_projects', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('epic_key', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_projects', schema=None) as batch_op:
        batch_op.drop_column('epic_key')

    # ### end Alembic commands ###
