"""add project_key to user_tableau_custom_views

Revision ID: f8954404f3b1
Revises: c3d00bc3ae67
Create Date: 2026-03-24 15:34:22.452609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8954404f3b1'
down_revision = 'c3d00bc3ae67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tableau_custom_views', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('project_key', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tableau_custom_views', schema=None) as batch_op:
        batch_op.drop_column('project_key')

    # ### end Alembic commands ###
